import Link from "next/link";

export default function NotFound() {
  return (
    <div
      style={{
        height: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#0f0f0f",
        color: "#fff",
        textAlign: "center",
        padding: "20px",
      }}
    >
      <h1 style={{ fontSize: "6rem", marginBottom: "20px" }}>404</h1>
      <h2 style={{ fontSize: "2rem", marginBottom: "20px" }}>الصفحة غير موجودة</h2>
      <p>الصفحة التي تحاول الوصول إليها غير موجودة أو تم نقلها.</p>
      <Link
        href="/"
        style={{
          marginTop: "30px",
          padding: "10px 20px",
          backgroundColor: "#ff4500",
          color: "#fff",
          borderRadius: "5px",
          textDecoration: "none",
        }}
      >
        العودة للرئيسية
      </Link>
    </div>
  );
}


export const metadata = {
  title: "خطأ 404 - الصفحة غير موجودة",
  description: "Generated by create next app",
};